packages:
  - packages/*
  - examples/*

nodeLinker: hoisted

allowBuilds:
  '@bitdisaster/exe-icon-extractor': true
  better-sqlite3: true
  electron: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  sharp: true
  usocket: set this to true or false
  workerd: true

overrides:
  '@electron/rebuild': ^4.2.0
  'happy-dom@<20.8.9': 20.11.1
  'nanoid@<3.3.17': 3.3.17
  'tmp@<0.2.6': 0.2.7
  'undici@>=7.0.0 <7.29.0': 7.29.0

minimumReleaseAgeExclude:
  - electron@43.3.0
