// src/shared/server-fn.ts
//
// Runtime render-phase guard. `render()` is strictly synchronous, so a server
// function invoked during render would either stringify its returned Promise as
// "[object Promise]" or leak server-only code (e.g. `this.c.db`) into the
// client bundle. The Cossack base class marks the render window via
// {@link enterRender}/{@link exitRender}; this module exposes the flag plus
// {@link assertNotRendering} for any code path that wants the same guard.

/**
 * Whether the framework is currently inside a synchronous render pass.
 * Incremented by {@link enterRender}, decremented by {@link exitRender}.
 */
let renderingDepth = 0;

export function enterRender(): void {
  renderingDepth++;
}

export function exitRender(): void {
  if (renderingDepth > 0) renderingDepth--;
}

export function isRendering(): boolean {
  return renderingDepth > 0;
}

const RENDER_GUARD_MESSAGE =
  '[Cossack] A server function cannot be called during render(). ' +
  'Use get()/init() to load data before render, or move the server call into ' +
  'an event handler. render() is synchronous and a server function would ' +
  'either stringify as "[object Promise]" or leak server-only code into the ' +
  'client bundle.';

/**
 * Whether the framework is running in production mode. Mirrors the convention
 * in `head.ts` (reads `globalThis.process.env.NODE_ENV`) so it works in Node
 * tests, Cloudflare Workers (where `process` may be polyfilled), and browser
 * bundles alike.
 */
function isProdEnv(): boolean {
  const env = (globalThis as any).process?.env?.NODE_ENV;
  return env === 'production';
}

/**
 * Throw (dev) or warn (prod) when called during a render pass.
 *
 * Used by the `@Server` client stubs generated by the security plugin (via the
 * base class' `__cossackAssertNotRendering`) so a stripped server method
 * invoked from `render()` fails loudly. Exported so user code or other
 * framework internals can apply the same guard.
 *
 * In development we throw so the misuse is loud. In production we warn only —
 * a mid-render throw would crash the page, while a warning still surfaces the
 * issue without breaking the user-facing render.
 */
export function assertNotRendering(): void {
  if (renderingDepth <= 0) return;
  if (isProdEnv()) {
    // eslint-disable-next-line no-console
    console.warn(RENDER_GUARD_MESSAGE);
    return;
  }
  throw new Error(RENDER_GUARD_MESSAGE);
}
