/*
 * GENERATED by `pnpm run build:icons`. Do not edit by hand.
 *
 * Aggregates all per-icon modules into a single lookup keyed by kebab name.
 * Add a new icon by dropping a module in ./generated and re-running the
 * build script.
 */
import type { IconRegistry } from "./types";
import { addCircle } from "./generated/AddCircle";
import { altArrowDown } from "./generated/AltArrowDown";
import { altArrowLeft } from "./generated/AltArrowLeft";
import { altArrowRight } from "./generated/AltArrowRight";
import { altArrowUp } from "./generated/AltArrowUp";
import { arrowDown } from "./generated/ArrowDown";
import { arrowLeft } from "./generated/ArrowLeft";
import { arrowRight } from "./generated/ArrowRight";
import { arrowUp } from "./generated/ArrowUp";
import { calendar } from "./generated/Calendar";
import { checkCircle } from "./generated/CheckCircle";
import { closeCircle } from "./generated/CloseCircle";
import { copy } from "./generated/Copy";
import { dangerCircle } from "./generated/DangerCircle";
import { dangerTriangle } from "./generated/DangerTriangle";
import { eye } from "./generated/Eye";
import { eyeClosed } from "./generated/EyeClosed";
import { filter } from "./generated/Filter";
import { hamburgerMenu } from "./generated/HamburgerMenu";
import { infoCircle } from "./generated/InfoCircle";
import { magnifier } from "./generated/Magnifier";
import { minusCircle } from "./generated/MinusCircle";
import { refresh } from "./generated/Refresh";
import { reorder } from "./generated/Reorder";
import { settings } from "./generated/Settings";
import { trashBinMinimalistic } from "./generated/TrashBinMinimalistic";
import { user } from "./generated/User";

export const iconRegistry: IconRegistry = {
    "add-circle": addCircle,
    "alt-arrow-down": altArrowDown,
    "alt-arrow-left": altArrowLeft,
    "alt-arrow-right": altArrowRight,
    "alt-arrow-up": altArrowUp,
    "arrow-down": arrowDown,
    "arrow-left": arrowLeft,
    "arrow-right": arrowRight,
    "arrow-up": arrowUp,
    "calendar": calendar,
    "check-circle": checkCircle,
    "close-circle": closeCircle,
    "copy": copy,
    "danger-circle": dangerCircle,
    "danger-triangle": dangerTriangle,
    "eye": eye,
    "eye-closed": eyeClosed,
    "filter": filter,
    "hamburger-menu": hamburgerMenu,
    "info-circle": infoCircle,
    "magnifier": magnifier,
    "minus-circle": minusCircle,
    "refresh": refresh,
    "reorder": reorder,
    "settings": settings,
    "trash-bin-minimalistic": trashBinMinimalistic,
    "user": user,
};

/** All registered icon names. */
export const iconNames = Object.keys(iconRegistry);
