/*
 * GENERATED by `pnpm run build:icons`. Do not edit by hand.
 *
 * Aggregates all per-icon modules into a single lookup keyed by kebab name.
 * Add a new icon by dropping a module in ./generated and re-running the
 * build script.
 */
import type { IconRegistry } from "./types";
import { arrowRight } from "./generated/ArrowRight";
import { check } from "./generated/Check";
import { close } from "./generated/Close";
import { warning } from "./generated/Warning";

export const iconRegistry: IconRegistry = {
    "arrow-right": arrowRight,
    check,
    close,
    warning,
};

/** All registered icon names. */
export const iconNames = Object.keys(iconRegistry);
