import type { Dialect } from "../adapter/types.js";
import { UnsupportedCapabilityError } from "../errors.js";
import type { ColumnSchema, EntitySchema } from "./types.js";
import type { SchemaOperation } from "./operations.js";

function literal(value: unknown): string {
  if (value === null) return "NULL";
  if (typeof value === "number" || typeof value === "bigint") return String(value);
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "string" && /^\w+\(\)$|^CURRENT_(TIMESTAMP|DATE|TIME)$/.test(value)) return value;
  return `'${String(value).replaceAll("'", "''")}'`;
}

export function columnDDL(column: ColumnSchema, dialect: Dialect): string {
  const options: Record<string, unknown> = {};
  if (column.length !== undefined) options.length = column.length;
  if (column.precision !== undefined) options.precision = column.precision;
  if (column.scale !== undefined) options.scale = column.scale;
  let type = dialect.mapType(column.logicalType, options);
  if (column.array) {
    if (!dialect.capabilities.arrays) throw new UnsupportedCapabilityError("array columns", dialect.name);
    type += "[]";
  }
  const parts = [dialect.quoteIdentifier(column.columnName), type];
  if (column.primary) parts.push("PRIMARY KEY");
  if (column.generated === "increment" && dialect.name === "sqlite") parts.push("AUTOINCREMENT");
  if (column.generated === "identity" && dialect.name === "postgres") parts.push("GENERATED BY DEFAULT AS IDENTITY");
  if (!column.nullable) parts.push("NOT NULL");
  if (column.unique) parts.push("UNIQUE");
  if (column.default !== undefined) parts.push("DEFAULT", literal(column.default));
  if (column.enumValues?.length) {
    parts.push(`CHECK (${dialect.quoteIdentifier(column.columnName)} IN (${column.enumValues.map(literal).join(", ")}))`);
  }
  return parts.join(" ");
}

function foreignKeys(entity: EntitySchema, dialect: Dialect): string[] {
  return entity.relations
    .filter((relation) => relation.owner && relation.physical && relation.joinColumn && relation.referencedColumn)
    .map((relation) => {
      const parts = [
        `FOREIGN KEY (${dialect.quoteIdentifier(relation.joinColumn!)})`,
        `REFERENCES ${dialect.quoteIdentifier(relation.targetTableName ?? relation.targetEntity)} (${dialect.quoteIdentifier(relation.referencedColumn!)})`,
      ];
      if (relation.onDelete) parts.push(`ON DELETE ${relation.onDelete}`);
      return parts.join(" ");
    });
}

export function createTableDDL(entity: EntitySchema, dialect: Dialect): string[] {
  const columns = entity.columns.map((column) => columnDDL(column, dialect));
  columns.push(...foreignKeys(entity, dialect));
  const statements = [
    `CREATE TABLE ${dialect.quoteIdentifier(entity.tableName)} (\n  ${columns.join(",\n  ")}\n)`,
  ];
  for (const index of entity.indexes) {
    statements.push(
      `CREATE${index.unique ? " UNIQUE" : ""} INDEX ${dialect.quoteIdentifier(index.name)} ` +
      `ON ${dialect.quoteIdentifier(entity.tableName)} (${index.columns.map((column) => dialect.quoteIdentifier(column)).join(", ")})`,
    );
  }
  for (const relation of entity.relations) {
    if (!relation.owner || !relation.joinTable) continue;
    const join = relation.joinTable;
    statements.push(
      `CREATE TABLE ${dialect.quoteIdentifier(join.name)} (\n` +
      `  ${dialect.quoteIdentifier(join.joinColumn)} ${dialect.mapType(join.referencedLogicalType)} NOT NULL,\n` +
      `  ${dialect.quoteIdentifier(join.inverseJoinColumn)} ${dialect.mapType(join.inverseReferencedLogicalType)} NOT NULL,\n` +
      `  PRIMARY KEY (${dialect.quoteIdentifier(join.joinColumn)}, ${dialect.quoteIdentifier(join.inverseJoinColumn)}),\n` +
      `  FOREIGN KEY (${dialect.quoteIdentifier(join.joinColumn)}) REFERENCES ${dialect.quoteIdentifier(entity.tableName)} (${dialect.quoteIdentifier(join.referencedColumn)}) ON DELETE CASCADE,\n` +
      `  FOREIGN KEY (${dialect.quoteIdentifier(join.inverseJoinColumn)}) REFERENCES ${dialect.quoteIdentifier(relation.targetTableName ?? relation.targetEntity)} (${dialect.quoteIdentifier(join.inverseReferencedColumn)}) ON DELETE CASCADE\n` +
      `)`,
    );
  }
  return statements;
}

export function renderOperation(operation: SchemaOperation, dialect: Dialect): readonly string[] {
  const q = dialect.quoteIdentifier.bind(dialect);
  switch (operation.kind) {
    case "create-table": return createTableDDL(operation.entity, dialect);
    case "drop-table": return [`DROP TABLE ${q(operation.tableName)}`];
    case "rename-table": return [`ALTER TABLE ${q(operation.from)} RENAME TO ${q(operation.to)}`];
    case "add-column": return [`ALTER TABLE ${q(operation.tableName)} ADD COLUMN ${columnDDL(operation.column, dialect)}`];
    case "drop-column": return [`ALTER TABLE ${q(operation.tableName)} DROP COLUMN ${q(operation.columnName)}`];
    case "rename-column": return [`ALTER TABLE ${q(operation.tableName)} RENAME COLUMN ${q(operation.from)} TO ${q(operation.to)}`];
    case "alter-column":
      if (dialect.name === "sqlite") {
        throw new UnsupportedCapabilityError(
          `direct SQLite alter column (${operation.tableName}.${operation.after.columnName}); generate a table-rebuild migration`,
          dialect.name,
        );
      }
      return [
        `ALTER TABLE ${q(operation.tableName)} ALTER COLUMN ${q(operation.after.columnName)} TYPE ` +
          dialect.mapType(operation.after.logicalType, {
            length: operation.after.length,
            precision: operation.after.precision,
            scale: operation.after.scale,
          }),
      ];
    case "create-index":
      return [
        `CREATE${operation.index.unique ? " UNIQUE" : ""} INDEX ${q(operation.index.name)} ` +
        `ON ${q(operation.tableName)} (${operation.index.columns.map(q).join(", ")})`,
      ];
    case "drop-index":
      return [dialect.name === "mysql"
        ? `DROP INDEX ${q(operation.indexName)} ON ${q(operation.tableName)}`
        : `DROP INDEX ${q(operation.indexName)}`];
  }
}
