import { loadStub } from './load-stub.js';

// Database stubs (`cossack generate model|migration|seeder`)
// ===========================================================================

/** `src/models/User.ts` — default User model + Database/User augmentations. */
export function userModelTemplate() {
  return loadStub('user-model.ts.stub');
}

/** A blank migration file generated by `cossack generate migration <name>`. */
export function migrationTemplate() {
  return loadStub('migration.ts.stub');
}

/** A blank seeder file generated by `cossack generate seeder <name>`. */
export function seederTemplate() {
  return loadStub('seeder.ts.stub');
}
