import { loadStub } from './load-stub.js';

// ORM stubs (`cossack generate model|migration|seeder`)
// ===========================================================================

/** `src/models/User.ts` — default decorated ORM entity. */
export function userModelTemplate({ className }) {
  return loadStub('user-model.ts.stub', { className });
}

/** A blank migration file generated by `cossack generate migration <name>`. */
export function migrationTemplate({ name }) {
  return loadStub('migration.ts.stub', { name });
}

/** A blank seeder file generated by `cossack generate seeder <name>`. */
export function seederTemplate({ name }) {
  return loadStub('seeder.ts.stub', { name });
}
