import type {
  EntitySchema,
  Migration,
} from "../../../src/index.js";

const users: EntitySchema = {
  modelName: "User",
  tableName: "users",
  virtual: false,
  columns: [
    {
      propertyName: "id",
      columnName: "id",
      logicalType: "integer",
      nullable: false,
      primary: true,
      generated: "increment",
      unique: false,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "email",
      columnName: "email",
      logicalType: "varchar",
      length: 255,
      nullable: false,
      primary: false,
      generated: false,
      unique: true,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "name",
      columnName: "name",
      logicalType: "varchar",
      length: 255,
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "createdAt",
      columnName: "created_at",
      logicalType: "datetime",
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      default: "CURRENT_TIMESTAMP",
      createDate: true,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "updatedAt",
      columnName: "updated_at",
      logicalType: "datetime",
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      default: "CURRENT_TIMESTAMP",
      updateDate: true,
      insert: true,
      update: true,
      select: true,
    },
  ],
  relations: [
    {
      propertyName: "posts",
      kind: "one-to-many",
      targetEntity: "Post",
      targetTableName: "posts",
      inverseProperty: "author",
      owner: false,
      nullable: true,
      physical: true,
      cascade: [],
    },
  ],
  indexes: [],
};

const posts: EntitySchema = {
  modelName: "Post",
  tableName: "posts",
  virtual: false,
  columns: [
    {
      propertyName: "id",
      columnName: "id",
      logicalType: "integer",
      nullable: false,
      primary: true,
      generated: "increment",
      unique: false,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "slug",
      columnName: "slug",
      logicalType: "varchar",
      length: 255,
      nullable: false,
      primary: false,
      generated: false,
      unique: true,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "title",
      columnName: "title",
      logicalType: "varchar",
      length: 255,
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "body",
      columnName: "body",
      logicalType: "text",
      nullable: true,
      primary: false,
      generated: false,
      unique: false,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "published",
      columnName: "published",
      logicalType: "boolean",
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      default: false,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "createdAt",
      columnName: "created_at",
      logicalType: "datetime",
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      default: "CURRENT_TIMESTAMP",
      createDate: true,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "updatedAt",
      columnName: "updated_at",
      logicalType: "datetime",
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      default: "CURRENT_TIMESTAMP",
      updateDate: true,
      insert: true,
      update: true,
      select: true,
    },
    {
      propertyName: "authorId",
      columnName: "author_id",
      logicalType: "integer",
      nullable: false,
      primary: false,
      generated: false,
      unique: false,
      insert: true,
      update: true,
      select: true,
    },
  ],
  relations: [
    {
      propertyName: "author",
      kind: "many-to-one",
      targetEntity: "User",
      targetTableName: "users",
      inverseProperty: "posts",
      owner: true,
      nullable: false,
      physical: true,
      joinColumn: "author_id",
      joinProperty: "authorId",
      referencedColumn: "id",
      referencedProperty: "id",
      cascade: [],
      onDelete: "CASCADE",
    },
  ],
  indexes: [
    {
      name: "idx_posts_author_id",
      columns: ["author_id"],
      unique: false,
    },
    {
      name: "idx_posts_created_at",
      columns: ["created_at"],
      unique: false,
    },
  ],
};

export default {
  name: "0001_create_users_and_posts",
  up({ schema }) {
    schema.createTable(users);
    schema.createTable(posts);
  },
  down({ schema }) {
    schema.dropTable("posts");
    schema.dropTable("users");
  },
} satisfies Migration;
