#!/usr/bin/env tsx
/*
 * @cossackframework/ui — icon build pipeline
 *
 * Reads SVG source files from a vendor/source directory and emits:
 *   - src/icons/generated/<Pascal>.ts    one module per icon
 *   - src/icons/registry.ts              aggregated lookup map
 *
 * Source layout (configure via SRC_DIR env var or default):
 *   <SRC_DIR>/
 *     Line/<Name>.svg
 *     Bold/<Name>.svg
 *     Duotone/<Name>.svg
 *     Broken/<Name>.svg
 *
 * <Name> is the raw Solar filename (e.g. "Alt Arrow Right"). It is converted
 * to kebab-case for the registry key and PascalCase for the module export.
 *
 * Usage:
 *   pnpm run build:icons                       # uses ./vendor/solar-icons
 *   SRC_DIR=/path/to/solar pnpm run build:icons
 *
 * Each emitted icon's inner SVG markup (everything inside <svg>...</svg>) is
 * extracted and `currentColor`-ified so the Icon component can recolor via CSS.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, "..", "..");
const SRC_DIR = process.env.SRC_DIR
    ? path.resolve(process.env.SRC_DIR)
    : path.resolve(PKG_ROOT, "vendor", "solar-icons");
const GEN_DIR = path.resolve(PKG_ROOT, "src", "icons", "generated");
const REGISTRY_FILE = path.resolve(PKG_ROOT, "src", "icons", "registry.ts");

const STYLES = ["line", "bold", "duotone", "broken"] as const;
type Style = (typeof STYLES)[number];

function toKebab(raw: string): string {
    return String(raw)
        .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
        .replace(/[_\s]+/g, "-")
        .replace(/-+/g, "-")
        .toLowerCase()
        .replace(/^-|-$/g, "");
}

function toPascal(raw: string): string {
    return String(raw)
        .split(/[-_\s.]+/)
        .filter(Boolean)
        .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
        .join("");
}

/** Extract the inner markup of an <svg> and normalize colors to currentColor. */
function extractInner(svg: string): string {
    const match = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
    if (!match) return "";
    return match[1]
        .replace(/\s*(stroke|fill)\s*=\s*"#?\s*(?:black|#000(?:000)?|rgb\(0\s*0\s*0\))?"/gi, '$1="currentColor"')
        .replace(/\s*stroke\s*=\s*"none"/gi, ' stroke="none"')
        .trim();
}

async function exists(p: string): Promise<boolean> {
    try {
        await fs.access(p);
        return true;
    } catch {
        return false;
    }
}

async function readStyleDirs(): Promise<Record<Style, Map<string, string>>> {
    const result = {} as Record<Style, Map<string, string>>;
    for (const style of STYLES) {
        const dir = path.join(SRC_DIR, style.charAt(0).toUpperCase() + style.slice(1));
        const map = new Map<string, string>();
        if (await exists(dir)) {
            const files = await fs.readdir(dir);
            for (const file of files) {
                if (!file.toLowerCase().endsWith(".svg")) continue;
                const base = file.replace(/\.svg$/i, "");
                const svg = await fs.readFile(path.join(dir, file), "utf8");
                map.set(toKebab(base), extractInner(svg));
            }
        }
        result[style] = map;
    }
    return result;
}

async function main() {
    if (!(await exists(SRC_DIR))) {
        console.error(
            `[build-icons] Source dir not found: ${SRC_DIR}\n` +
                "Set SRC_DIR or place Solar SVGs under vendor/solar-icons/{Line,Bold,Duotote,Broken}/.",
        );
        process.exit(1);
    }

    console.log(`[build-icons] Reading source: ${SRC_DIR}`);
    const byStyle = await readStyleDirs();

    // Union of all icon names across styles.
    const names = new Set<string>();
    for (const style of STYLES) for (const n of byStyle[style].keys()) names.add(n);
    if (names.size === 0) {
        console.warn("[build-icons] No SVGs found. Nothing to do.");
        return;
    }

    await fs.mkdir(GEN_DIR, { recursive: true });

    const sorted = [...names].sort();
    const imports: string[] = [];
    const registryEntries: string[] = [];

    for (const name of sorted) {
        const pascal = toPascal(name);
        const safeProp = name.replace(/-/g, "") || pascal;
        // Actually use the kebab name as the key but camelCase as the JS prop.
        const camelProp =
            safeProp.charAt(0).toLowerCase() + safeProp.slice(1);

        const styles: string[] = [];
        for (const style of STYLES) {
            const inner = byStyle[style].get(name);
            if (inner) styles.push(`    ${style}: ${JSON.stringify(inner)},`);
        }

        const moduleSource = `/*
 * GENERATED by \`pnpm run build:icons\`. Do not edit by hand.
 * Source: Solar icon set (https://solar-icons.vercel.app/).
 */
import type { IconEntry } from "../types";

export const ${camelProp}: IconEntry = {
${styles.join("\n")}
};
`;

        const outFile = path.join(GEN_DIR, `${pascal}.ts`);
        await fs.writeFile(outFile, moduleSource, "utf8");
        imports.push(`import { ${camelProp} } from "./generated/${pascal}";`);
        registryEntries.push(
            `    ${JSON.stringify(name)}: ${camelProp},`,
        );
    }

    const registrySource = `/*
 * GENERATED by \`pnpm run build:icons\`. Do not edit by hand.
 *
 * Aggregates all per-icon modules into a single lookup keyed by kebab name.
 * Add a new icon by dropping a module in ./generated and re-running the
 * build script.
 */
import type { IconRegistry } from "./types";
${imports.join("\n")}

export const iconRegistry: IconRegistry = {
${registryEntries.join("\n")}
};

/** All registered icon names. */
export const iconNames = Object.keys(iconRegistry);
`;

    await fs.writeFile(REGISTRY_FILE, registrySource, "utf8");
    console.log(
        `[build-icons] Emitted ${sorted.length} icon(s) → ${path.relative(PKG_ROOT, GEN_DIR)}`,
    );
    console.log(`[build-icons] Registry → ${path.relative(PKG_ROOT, REGISTRY_FILE)}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
