// src/router.ts
import 'reflect-metadata';
import { Hono, type Context, type Handler } from 'hono';
import { renderRoot } from './root';
import { PageOptions, Cossack, AuthenticatedUser } from '@cossackframework/core';
import { App } from './App';
import { createApiHandler } from './api-handler';
import registry from 'virtual:cossack-pages';
// @ts-expect-error - this file is generated by vite and may not exist at design time
import manifest from '~/.vite/manifest.json';
import { CossackElement } from '@cossackframework/renderer';

const { pages, layouts, components, loadings } = registry;

/**
 * Convert a file path to a simplified route path.
 * Example: /src/pages/hello/[name]/index.ts -> /hello/[name]
 */
function filePathToRoutePath(filePath: string): string {
    const route = filePath
        .replace('/src/pages/', '/')
        .replace('/index.ts', '')
        .replace('/index.mdx', '')
        .replace(/\.(ts|tsx|mdx)$/, '');

    // Normalize root: /index (from pages/index/index.ts) or empty (from pages/index.ts) -> /
    if (route === '/index' || route === '') {
        return '/';
    }
    return route;
}

// Register Components
for (const path in components) {
    const module = components[path];
    // Find the exported class
    for (const key in module) {
        const exported = (module as any)[key];
        if (typeof exported === 'function' && (exported.prototype instanceof CossackElement || (exported as any)._isCossackElement)) {
            // Register by export name
            CossackElement.components[key] = exported;
        }
    }
}

// Generate secure IDs for components
const routeIdMap = new Map<string, string>();
const routePathToIdMap = new Map<string, string>();
const routePathToFilePathMap = new Map<string, string>();

// Register the App component (global component) with a special ID
const APP_ID = 'cossack_app';
routeIdMap.set(APP_ID, '/src/App');

[...Object.keys(pages), ...Object.keys(layouts)].sort().forEach((path, index) => {
    const id = `cmp_${index.toString(36)}`;
    routeIdMap.set(id, path);
    routePathToIdMap.set(path, id);
    // Map route path to file path for WebSocket connections
    const routePath = filePathToRoutePath(path);
    routePathToFilePathMap.set(routePath, path);
});

export type PageModule = {
    [key: string]: (new () => Cossack) | Handler | Record<string, Handler>;
}

function getLayoutStack(pagePath: string) {
    const stack: string[] = [];
    const relativePath = pagePath.replace('/src/pages/', '');
    const parts = relativePath.split('/');
    
    let currentPath = '/src/pages';
    
    if (layouts[`${currentPath}/layout.ts`]) {
        stack.push(`${currentPath}/layout.ts`);
    }
    
    for (let i = 0; i < parts.length - 1; i++) {
        currentPath += `/${parts[i]}`;
        const layoutPath = `${currentPath}/layout.ts`;
        if (layouts[layoutPath]) {
            stack.push(layoutPath);
        }
    }
    
    return stack;
}

function findNearestSpecialPage(pagePath: string, type: '404' | 'error') {
    const relativePath = pagePath.replace('/src/pages/', '');
    const parts = relativePath.split('/');
    
    for (let i = parts.length - 1; i >= 0; i--) {
        const dir = parts.slice(0, i).join('/');
        const searchPath = dir 
            ? `/src/pages/${dir}/${type}/index.ts`
            : `/src/pages/${type}/index.ts`;
            
        if (pages[searchPath]) {
            return { path: searchPath, component: Object.values(pages[searchPath] as object)[0] as new () => Cossack };
        }
    }
    
    return null;
}

export interface CreateAppOptions {
  authMiddleware?: (c: any, next: () => Promise<void>) => Promise<void>;
  AppComponent?: new (...args: any[]) => Cossack;
}

export function createApp(options: CreateAppOptions = {}) {
    const app = new Hono<{ Bindings: CloudflareBindings, Variables: { user?: AuthenticatedUser } }>();

    // Authentication middleware - use custom or default (no-op)
    app.use('*', (c, next) => {
        if (options.authMiddleware) {
            return options.authMiddleware(c, next);
        }
        return next();
    });

    const createSsrHandler = (PageComponent: new () => Cossack, path: string, pageOptions?: PageOptions) => {
        return async (c: Context) => {
            try {
                const user = c.get('user');
                const appInstance = new (options.AppComponent ?? App)();
                const layoutInstances: any[] = [];
                const pageInstance = new PageComponent();
                const layoutPaths = getLayoutStack(path);

                // Check if component has a loading template (method or file convention)
                // If so, skip init() during SSR to show loading UI immediately
                const hasLoadingTemplate = typeof (pageInstance as any).loadingTemplate === 'function';
                const lastSlash = path.lastIndexOf('/');
                const loadingFilePath = `${path.substring(0, lastSlash)}/loading.ts`;
                const hasLoadingFile = loadings[loadingFilePath] !== undefined;
                const shouldSkipInit = hasLoadingTemplate || hasLoadingFile;

                // For durable-object transport, query the DO for existing state before SSR
                let doInitialState: any = undefined;
                if (pageOptions?.transport === 'durable-object') {
                    try {
                        const doBinding = c.env.COSSACK_OBJECT;
                        // Use the full URL (path + query string) for DO ID
                        // This ensures different states for:
                        // - /hello/tan vs /hello/trang (dynamic routes)
                        // - /items?page=1 vs /items?page=2 (query params)
                        const id = doBinding.idFromName(c.req.url);
                        const stub = doBinding.get(id);

                        // Build query params for on-demand DO initialization
                        // Pass the file path since the DO registry is keyed by file path
                        const queryParams = new URLSearchParams({
                            componentPath: path,
                            url: c.req.url,
                            providerName: 'page',
                            params: JSON.stringify(c.req.param() || {}),
                        });

                        // Query the DO for current state via HTTP
                        const stateRequest = new Request(`http://dummy.local/state?${queryParams.toString()}`, {
                            method: 'GET',
                        });
                        const stateResponse = await stub.fetch(stateRequest);
                        if (stateResponse.ok) {
                            const responseData = await stateResponse.json();
                            // Extract public state from SerializedComponentState
                            if (responseData.public) {
                                doInitialState = responseData.public;
                            } else if (!responseData.error) {
                                // If no public field but no error, use the response directly
                                doInitialState = responseData;
                            }
                        }
                    } catch (e) {
                        // DO might not exist yet, or other error - proceed with default state
                        console.log('[Cossack] Could not query DO state:', e);
                    }
                }

                // Bootstrap App
                await appInstance.bootstrap({ context: c, user, env: c.env, page: c.req.path });

                // Bootstrap Layouts
                const layoutStates: Record<string, any> = {};
                for (const lPath of layoutPaths) {
                    const LComp = Object.values(layouts[lPath] as object)[0] as new () => Cossack;
                    const lInst = new LComp();
                    await lInst.bootstrap({ context: c, user, env: c.env, page: c.req.path });
                    layoutInstances.push(lInst);
                    layoutStates[lPath] = lInst.getInitialState();
                }

                // Bootstrap Page with retrieved DO initial state (if any)
                // Skip init() if component has a loading template to show loading UI immediately
                await pageInstance.bootstrap({
                    context: c,
                    user,
                    env: c.env,
                    page: c.req.path,
                    initialState: doInitialState,
                    skipInit: shouldSkipInit
                });

                // If we skipped init, set loading state so loadingTemplate() renders during SSR
                // The client will then call init() via RPC to get the actual data
                if (shouldSkipInit) {
                    (pageInstance as any).loading.init = 1;
                }
                
                // Force render to populate registry
                pageInstance._render();
                
                // Wrap rendering
                let body = (pageInstance as any)._getWrappedTemplate();
                for (let i = layoutInstances.length - 1; i >= 0; i--) {
                    layoutInstances[i].children = body;
                    body = layoutInstances[i]._getWrappedTemplate();
                }
                appInstance.children = body;
                const finalHtml = appInstance._render();

                // Head Merging
                const emptyCtx = Cossack.buildHeadContext([]);
                const pageHeadValue = pageInstance.head(emptyCtx);
                let tags = Cossack.mergeHead(emptyCtx, pageHeadValue);
                for (let i = layoutInstances.length - 1; i >= 0; i--) {
                    const headContext = Cossack.buildHeadContext(tags);
                    const headValue = layoutInstances[i].head(headContext);
                    tags = Cossack.mergeHead(headContext, headValue);
                }
                const finalHeadContext = Cossack.buildHeadContext(tags);
                const appHeadValue = appInstance.head(finalHeadContext);
                const headTags = Cossack.mergeHead(finalHeadContext, appHeadValue);

                const pageInitialState = pageInstance.getInitialState();

                // For durable-object transport, add the DO ID to providerTargets
                // Also add routePath to metadata for client WebSocket connections
                if (pageOptions?.transport === 'durable-object') {
                    const doBinding = c.env.COSSACK_OBJECT;
                    // Use the full URL for DO ID so query params create separate DOs
                    const doId = doBinding.idFromName(c.req.url);
                    // Convert DurableObjectId to string for client-side use
                    pageInitialState.providerTargets = {
                        ...(pageInitialState.providerTargets || {}),
                        page: doId.toString()
                    };
                    // Add routePath to metadata for client WebSocket connections
                    if (pageInitialState.metadata) {
                        pageInitialState.metadata.routePath = filePathToRoutePath(path);
                    }
                }

                const finalInitialState = {
                    ...pageInitialState,
                    routePath: filePathToRoutePath(path),  // Simplified route path (no /src/pages prefix)
                    componentRouteId: routePathToIdMap.get(path),
                    appRouteId: 'cossack_app',  // Route ID for the App component (root)
                    pathname: c.req.path,
                    channels: pageOptions?.channels || ['global'],
                    _app_state: appInstance.getInitialState(),
                    _layout_stack: layoutPaths.map(p => ({ path: p, state: layoutStates[p] })) // Keep file paths for layouts
                };

                c.header('Content-Type', 'text/html');
                return c.body(renderRoot({ body: finalHtml, initialState: finalInitialState, manifest, headTags }));
            } catch (err) {
                console.error('[Cossack SSR Error]:', err);
                const errorPage = findNearestSpecialPage(path, 'error');
                if (errorPage && path !== errorPage.path) {
                    const handler = createSsrHandler(errorPage.component, errorPage.path);
                    return handler(c);
                }
                return c.html(`<h1>Internal Server Error</h1><pre>${err instanceof Error ? err.stack : err}</pre>`, 500);
            }
        };
    };

    app.get('/ws/:provider/:id', async (c) => {
        const user = c.get('user');
        const { provider, id: durableObjectId } = c.req.param();
        const routePath = c.req.query('routePath');
        // Support both routePath (new) and componentPath (legacy) for backward compatibility
        const componentPathQuery = routePath || c.req.query('componentPath');
        if (!componentPathQuery) return new Response('routePath or componentPath query parameter is required', { status: 400 });

        // Convert route path to file path if needed
        const componentPath = routePathToFilePathMap.get(componentPathQuery) || componentPathQuery;

        const doBinding = c.env.COSSACK_OBJECT;
        const id = doBinding.idFromString(durableObjectId);
        const stub = doBinding.get(id);
        const request = new Request(c.req.raw);
        
        request.headers.set('X-Component-Path', componentPath);
        request.headers.set('X-Provider-Name', provider);
        if (user) {
            request.headers.set('X-User-ID', user.id);
            request.headers.set('X-User-Data', JSON.stringify(user));
        }

        return await stub.fetch(request);
    });

    app.post('/upload', async (c) => {
        const body = await c.req.parseBody({ all: true });
        const componentRouteId = body.componentRouteId as string;
        const action = body.action as string;
        const target = body.target as string;
        const stateStr = body.state as string;
        const payloadStr = body.payload as string;

        if (!componentRouteId || !action) return c.json({ error: 'Missing componentRouteId or action' }, 400);

        const componentPath = routeIdMap.get(componentRouteId);
        if (!componentPath) return c.json({ error: 'Invalid component ID' }, 400);

        const state = stateStr ? JSON.parse(stateStr) : {};
        const payload = payloadStr ? JSON.parse(payloadStr) : [];

        // Reconstruct arguments with files
        const args = payload.map((arg: any) => {
            if (arg && typeof arg === 'object' && arg._cossack_file_id) {
                const fileId = arg._cossack_file_id;
                const file = body[fileId];
                return file;
            }
            return arg;
        });

        const user = c.get('user');
        const module = pages[componentPath] || layouts[componentPath];
        if (!module) return c.json({ error: 'Component not found' }, 404);
        const PageComponent = Object.values(module as object)[0] as new () => Cossack;
        if (!PageComponent || typeof PageComponent !== 'function') return c.json({ error: 'Invalid component' }, 500);

        const componentInstance = new PageComponent() as any;
        await componentInstance.bootstrap({ context: c, user, env: c.env, skipInit: true });

        // Rebuild component tree to find target
        componentInstance._render();

        let targetInstance = componentInstance;
        if (target && target !== targetInstance._id) {
            if (targetInstance.activeComponents.has(target)) {
                targetInstance = targetInstance.activeComponents.get(target);
            } else {
                // Warning only, fall back to root or error?
                // For HTTP, if target missing, action likely fails.
                return c.json({ error: `Target component '${target}' not found` }, 404);
            }
        }

        // Apply the received state directly to the target component
        // The state sent from client is the target component's public state
        for (const key in state) {
            (targetInstance as any)[key] = state[key];
        }

        if (typeof targetInstance[action] !== 'function') return c.json({ error: `Action '${action}' not found` }, 404);

        const actionResult = await targetInstance[action](...args);

        const location = c.res.headers.get('Location');
        if (location) return c.json({ _cossack_redirect: location });
        if (actionResult instanceof Response) return actionResult;

        // Get the state of the component that was actually modified
        const responseData = targetInstance.getPublicState();
        if (actionResult !== undefined) {
            (responseData as any)._cossack_return = actionResult;
        }

        return c.json(responseData);
    });

    app.post('/crpc', async (c) => {
        const { componentRouteId, action, state, payload, target } = await c.req.json();
        const user = c.get('user');

        const componentPath = routeIdMap.get(componentRouteId);
        if (!componentPath) return c.json({ error: 'Invalid component ID' }, 400);

        // Handle App component (global component) specially
        let componentInstance: any;
        if (componentPath === '/src/App') {
            componentInstance = new (options.AppComponent ?? App)();
            await componentInstance.bootstrap({ context: c, user, env: c.env, skipInit: true });
            componentInstance._render();
        } else {
            const module = pages[componentPath] || layouts[componentPath];
            if (!module) return c.json({ error: 'Component not found' }, 404);
            const PageComponent = Object.values(module as object)[0] as new () => Cossack;
            if (!PageComponent || typeof PageComponent !== 'function') return c.json({ error: 'Invalid component' }, 500);
            componentInstance = new PageComponent() as any;
            await componentInstance.bootstrap({ context: c, user, env: c.env, skipInit: true });

            // Rebuild component tree
            componentInstance._render();
        }

        let targetInstance = componentInstance;
        if (target && target !== targetInstance._id) {
            if (targetInstance.activeComponents.has(target)) {
                targetInstance = targetInstance.activeComponents.get(target);
            } else {
                return c.json({ error: `Target component '${target}' not found` }, 404);
            }
        }

        // Apply the received state directly to the target component
        // The state sent from client is the target component's public state
        for (const key in state) {
            (targetInstance as any)[key] = state[key];
        }

        if (typeof targetInstance[action] !== 'function') return c.json({ error: `Action '${action}' not found` }, 404);
        const actionResult = await targetInstance[action](...(payload || []));
        const location = c.res.headers.get('Location');
        if (location) return c.json({ _cossack_redirect: location });
        if (actionResult instanceof Response) return actionResult;

        // Get the state of the component that was actually modified
        const responseData = targetInstance.getPublicState();
        if (actionResult !== undefined) {
            (responseData as any)._cossack_return = actionResult;
        }
        return c.json(responseData);
    });

    // Register all routes
    for (const path in pages) {
        let httpRoute = path
            .replace('/src/pages', '')
            .replace(/\.(ts|tsx|js|jsx|mdx)$/, '')
            .replace(/\/index$/, '')
            .replace(/\/\([^)]+\)/g, '')
            .replace(/\[([^\]]+)\]/g, ':$1') || '/';

        if (httpRoute === '/index') httpRoute = '/';
        if (httpRoute.endsWith('/404') || httpRoute.endsWith('/error')) continue;

        const module = pages[path] as any;
        const mainExport = Object.values(module)[0];

        // 1. Check if it's a Cossack Component
        if (mainExport && typeof mainExport === 'function' && mainExport.prototype instanceof Cossack) {
            const PageComponent = mainExport as new () => Cossack;
            const pageOptions: PageOptions | undefined = Reflect.getMetadata('page:options', PageComponent);
            const layoutPaths = getLayoutStack(path);
            const combinedMiddlewares = [];
            for (const lPath of layoutPaths) {
                const LComp = Object.values(layouts[lPath] as object)[0] as new () => Cossack;
                const lOpts = Reflect.getMetadata('page:options', LComp);
                if (lOpts?.middlewares) combinedMiddlewares.push(...lOpts.middlewares);
            }
            if (pageOptions?.middlewares) combinedMiddlewares.push(...pageOptions.middlewares);

            const ssrHandler = createSsrHandler(PageComponent, path, pageOptions);
            if (pageOptions?.transport !== 'http') {
                Reflect.defineMetadata('cossack:durable-object-name', 'COSSACK_OBJECT', PageComponent);
            }
            app.get(httpRoute, ...combinedMiddlewares, ssrHandler);

            // Handle class-based HTTP method handlers for hybrid pages
            // This allows pages to both render HTML AND handle API requests (e.g., form POST)
            if (pageOptions?.transport === 'http') {
                const httpMethods = ['post', 'put', 'patch', 'delete'];
                for (const method of httpMethods) {
                    if (method in PageComponent.prototype) {
                        (app as any)[method](httpRoute, ...combinedMiddlewares, createApiHandler(PageComponent, method));
                    }
                }
            }
        } 
        // 2. Check if it's a functional API Route
        else if (path.includes('/src/pages/api/')) {
            // Handle default export as a generic handler
            if (typeof module.default === 'function') {
                app.all(httpRoute, module.default);
            } 
            // Handle named exports for HTTP methods (Nuxt/Next style)
            const methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'];
            for (const m of methods) {
                if (typeof module[m] === 'function') {
                    (app as any)[m.toLowerCase()](httpRoute, module[m]);
                }
            }
        }
    }

    app.notFound(async (c) => {
        const virtualPath = `/src/pages${c.req.path.replace(/\/$/, '')}/index.ts`;
        const notFoundPage = findNearestSpecialPage(virtualPath, '404');
        if (notFoundPage) return createSsrHandler(notFoundPage.component, notFoundPage.path)(c);
        return c.text('404 Not Found', 404);
    });

    return app;
}